const sidebars = {
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  记录: [
    "records/abouts"
  ],

  视频: [
    "videos/video1"
  ],

  关于: [
    "about"
  ],

};

module.exports = sidebars;
